"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

type Language = "en" | "fr" | "ar"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Navigation
    dashboard: "Dashboard",
    patients: "Patients",
    analytics: "Analytics",
    settings: "Settings",
    todayTransfusions: "Today's Transfusions",
    tomorrowTransfusions: "Tomorrow's Transfusions",
    history: "History",
    reports: "Reports",
    analyse: "Analysis",

    // Patient Table Headers
    nomEtPrenom: "NAME",
    gp: "GP",
    ph: "PH",
    f: "F",
    c: "C",
    l: "L",
    derniereT: "LAST T",
    prochaineT: "NEXT T",
    jecoulés: "DAYS ELAPSED",
    renseignements: "ACTIONS",
    bloodType: "Blood Type",
    lastTransfusion: "Last Transfusion",
    nextTransfusion: "Next Transfusion",

    // Actions
    view: "View",
    edit: "Edit",
    delete: "Delete",
    schedule: "Schedule",
    done: "Done",
    completed: "Completed",
    markAsDone: "Mark as Done",
    add: "Add",
    create: "Create",
    update: "Update",
    remove: "Remove",
    back: "Back to Patients",
    age: "Age",
    years: "years",

    // Common
    loading: "Loading...",
    save: "Save",
    saving: "Saving...",
    cancel: "Cancel",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    export: "Export",
    import: "Import",
    noData: "No data available",

    // Dashboard
    totalPatients: "Total Patients",
    urgentCases: "Urgent Cases",
    activeTransfusions: "Active Transfusions",
    scheduledTransfusions: "Scheduled Transfusions",
    completedToday: "Completed Today",

    // Scheduling
    scheduleTransfusion: "Schedule Transfusion",
    regular: "Regular",
    urgent: "Urgent",
    scheduledForTomorrow: "Scheduled for tomorrow at 9:00 AM",
    scheduledForToday: "Scheduled for today at next available slot",
    selectDate: "Select Date",
    selectTime: "Select Time",
    selectType: "Select Type",

    // Forms
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email",
    phone: "Phone",
    address: "Address",
    dateOfBirth: "Date of Birth",
    gender: "Gender",
    bloodGroup: "Blood Group",
    rhFactor: "RH Factor",
    note: "Note",
    notes: "Notes",
    reason: "Reason",
    status: "Status",

    // Status
    pending: "Pending",
    inProgress: "In Progress",
    cancelled: "Cancelled",
    successful: "Successful",
    failed: "Failed",

    // Settings
    language: "Language",
    selectLanguage: "Select Language",
    theme: "Theme",
    darkMode: "Dark Mode",
    notifications: "Notifications",
    soundEnabled: "Sound Enabled",
    emailNotifications: "Email Notifications",
    updateProfile: "Update Profile",
    changePassword: "Change Password",
    logout: "Logout",
    myProfile: "My Profile",
    profileSettings: "Profile Settings",

    // Analytics
    totalTransfusions: "Total Transfusions",
    numberOfBags: "Number of Bags",
    avgHemoglobin: "Average Hemoglobin",
    criticalCases: "Critical Cases",
    activePatients: "Active Patients",
    transfusionsToday: "Transfusions Today",
    rarePhenotypes: "Rare Phenotypes",
    dominantBloodType: "Dominant Blood Type",
    chartsAndTrends: "Charts and Trends",
    transfusionDataVisualization: "Visual representation of transfusion data",
    transfusionsAndBags: "Transfusions and Blood Bags",
    transfusionsScheduledVsCompleted: "Scheduled transfusions vs completed with number of bags",
    bloodGroupsAndHemoglobin: "Blood Groups and Hemoglobin",
    hemoglobinDistribution: "Distribution with average hemoglobin level",
    prioritiesAndBags: "Priorities and Blood Bags",
    distributionByPriority: "Distribution by priority with number of bags",
    monthlyTrends: "Monthly Trends",
    transfusionByMonth: "Transfusions by month with progress",
    vsLastWeek: "vs last week",
    vsLastPeriod: "vs last period",
    bagPerTransfusion: "bags per transfusion",
    range: "Range",
    newPatients: "new patients",
    patients: "patients",
    completed: "completed",
    data: "Data",
    chart: "Chart",
    no: "No",

    // Transfusions
    noTransfusionScheduled: "No Transfusion Scheduled",
    noBloodTransfusionsScheduled: "There are no blood transfusions scheduled for tomorrow",
    noBloodTransfusionsScheduledToday: "There are no blood transfusions scheduled for today",
    print: "Print",
    dailyTransfusionReport: "Daily Transfusion Report",
    transfusionSchedule: "Blood Transfusion Schedule",
    confirmDeleteTransfusion: "Are you sure you want to delete this transfusion?",
    deleted: "Deleted",
    transfusionDeleted: "Transfusion successfully deleted",
    deletionFailed: "Failed to delete transfusion",

    // Patient Management
    patientRecords: "Patient Records",
    manageAllPatients: "Manage all patient records and transfusion history",
    patientFound: "No patient found",
    tryAdjustingSearch: "Try adjusting your search criteria or filters.",
    addNewPatient: "Add New Patient",
    errorLoadingPatients: "Error loading patients",
    failedLoadingPatients: "An error occurred while loading patient data. Please try again.",
    retry: "Retry",
    patientInformation: "Patient Information",
    contactInformation: "Contact Information",
    contactDetailsDescription: "Update the patient's contact details and emergency information.",
    medicalInformation: "Medical Information",
    medicalDetailsDescription: "Update the patient's blood type, medical history, and transfusion details.",
    positive: "Positive",
    negative: "Negative",
    selectAdmissionDate: "Select admission date",
    selectLastTransfusionDate: "Select last transfusion date",
    patientAttributes: "Patient Attributes",
    selectPatientCategory: "Select patient category",
    pathology: "Pathology",
    alloImmunisationStatus: "Allo-immunization Status",
    transfusionHistory: "Transfusion History",
    patientActive: "Active Patient",
    neverTransfused: "Never transfused",
    notProvided: "Not provided",
    notAvailable: "N/A",
    editPersonalInfo: "Edit your personal information",
    bloodType: "Blood Type",
    height: "Height (cm)",
    hemoglobinLevel: "Hemoglobin Level (g/dL)",
    admissionDate: "Admission Date",
    lastTransfusionDate: "Last Transfusion Date",
    medicalHistory: "Medical History",
    emergencyContact: "Emergency Contact",
    emergencyPhone: "Emergency Phone",
    male: "Male",
    female: "Female",
    hyperRegime: "HyperRegimen",
    polyTransfused: "PolyTransfused",
    exchanges: "Exchanges",
    occasionalExchanges: "Occasional Exchanges",
    patientCategory: "Patient Category",
    selectPatientCategory: "Select patient category",
    pathologyPlaceholder: "Enter the patient's pathology details...",
    alloImmunisationStatusPlaceholder: "Enter allo-immunization status...",
    medicalHistoryAndNotes: "Medical History and Notes",
    medicalHistoryPlaceholder: "Enter relevant medical history, allergies, medications, or special notes...",
    allPatients: "All Patients",
    addPatient: "Add Patient",
    editPatient: "Edit Patient",
    savePatient: "Save Patient",
    deletePatientConfirm: "Are you sure you want to delete this patient? This action cannot be undone.",
    deletePatient: "Delete Patient",
    patientDeleted: "Patient successfully deleted",
    patientAdded: "Patient successfully added",
    patientAddedMessage: "The new patient has been added successfully.",
    patientUpdated: "Patient successfully updated",
    patientUpdatedMessage: "The patient information has been updated successfully.",
    failedToSavePatient: "Failed to save patient details. Please try again.",
    validationError: "Validation Error",
    selectGender: "Please select a gender.",
    selectCategory: "Please select a category.",
    selectBloodType: "Please select a blood type.",
    selectPhenotype: "Please select a phenotype.",
    scheduleTransfusionNow: "Schedule Transfusion Now",
    scheduleRegular: "Schedule Regular",
    scheduleUrgent: "Schedule Urgent",
    scheduleForToday: "Scheduled for today at 2:00 PM",
    scheduleForTomorrow: "Scheduled for tomorrow at 9:00 AM",
    failedScheduling: "Failed to schedule transfusion. Please try again.",
    daysElapsed: "Days Elapsed",
    searchPatients: "Search Patients",
    bloodTypeFilter: "Blood Type",
    phenotypeFilter: "Phenotype",
    actions: "Actions",
    viewDetails: "View Details",
    editDetails: "Edit Details",

    // History and Transfusion Pages
    addPatientForDay: "Add patient for this day",
    addTransfusion: "Add Transfusion",
    selectPatient: "Select a patient",
    priority: "Priority",
    bags: "Bags",
    hdist: "H.dist",
    hreceived: "H.received",
    noTransfusionFound: "No transfusion found.",
    phenotype: "Phenotype",
    hasF: "F",
    hasC: "C",
    hasL: "L",
    presence: "Presence",
    absent: "Absent",
    present: "Present",
    patient: "Patient",
    don: "Don",
    normale: "Normal",
    urgente: "Urgent",
    chuAnnaba: "CHU ANNABA SERVICE OF HEMOBIOLOGY AND BLOOD TRANSFUSION",
    chefDeService: "HEAD OF SERVICE PR. BROUK HACENE",
    patientNotFound: "Patient not found",
    noPastSchedules: "No past transfusion schedules.",
    date: "Date",
    modifierHbPostTransfusion: "Edit Hb Post Transfusion",
    hbPostTransfusion: "Hb Post Transfusion",
    misAJour: "Updated",
    hbfUpdated: "HbF successfully updated.",
    hbPostTransfusionOf: "Hb Post Transfusion of",
    previous: "Previous",
    next: "Next",
    showingPatients: "Showing {count} patients",
    searchByPatientName: "Search by patient name...",
    showingTransfusionsMatching: 'Showing {count} of {total} transfusions matching "{query}"',
    showingTransfusionsScheduled: "Showing {count} transfusions scheduled for today",
    transfusionsSummary: "({completed} completed, {pending} pending)",
    totalOrders: "{count} total orders",
    deliveredOrders: "({count} orders delivered)",
    urgentTransfusions: "Urgent Transfusions",
    markCompleted: "Mark completed",
    unmarkCompleted: "Unmark completed",
    patientRecordsReport: "BloodCare - Patient Records Report",
    hbPT: "Hb PT",
    yesLabel: "Yes",
    noLabel: "No",
    managementSystem: "Management System",
    closeNav: "Close navigation menu",
    openNav: "Open navigation menu",
    expandSidebar: "Expand sidebar",
    collapseSidebar: "Collapse sidebar",
    editTransfusion: "Edit Transfusion",
    transfusionDetails: "Transfusion Details",
    updateTransfusionDetailsDescription: "Update patient's transfusion details and blood unit information.",
    transfusionUpdated: "Transfusion successfully updated.",
    transfusionUpdatedDescription: "The transfusion information has been updated successfully.",
    deletePatientConfirmTitle: "Are you absolutely sure?",
    deletePatientConfirmDescription: "This action cannot be undone. This will permanently delete the patient record and all associated data.",
    patientDeletedTitle: "Patient deleted",
    patientDeletedDescription: "The patient has been successfully deleted.",
    deletePatientFailed: "Failed to delete patient. Please try again.",
    deletePatientTooltip: "Delete Patient",
    deleting: "Deleting...",
    allOrders: "all orders",
    ordersDelivered: "orders delivered",
    transfusionsScheduledForToday: "transfusions scheduled for today",

    // Messages
    success: "Success",
    error: "Error",
    warning: "Warning",
    info: "Information",
    confirmDelete: "Are you sure you want to delete this?",
    confirmLogout: "Are you sure you want to logout?",
    invalidInput: "Invalid input",
    required: "Please fill in all required fields marked with an asterisk (*)",
  },
  fr: {
    // Navigation
    dashboard: "Tableau de Bord",
    patients: "Patients",
    analytics: "Analyses",
    settings: "Paramètres",
    todayTransfusions: "Transfusions d'Aujourd'hui",
    tomorrowTransfusions: "Transfusions de Demain",
    history: "Historique",
    reports: "Rapports",
    analyse: "Analyse",

    // Patient Table Headers
    nomEtPrenom: "NOM ET PRÉNOM",
    gp: "GP",
    ph: "PH",
    f: "F",
    c: "C",
    l: "L",
    derniereT: "DERNIÈRE T",
    prochaineT: "PROCHAINE T",
    jecoulés: "J/ÉCOULÉS",
    renseignements: "ACTIONS",
    bloodType: "Groupe Sanguin",
    lastTransfusion: "Dernière Transfusion",
    nextTransfusion: "Prochaine Transfusion",

    // Actions
    view: "Voir",
    edit: "Modifier",
    delete: "Supprimer",
    schedule: "Programmer",
    done: "Terminé",
    completed: "Complété",
    markAsDone: "Marquer comme Terminé",
    add: "Ajouter",
    create: "Créer",
    update: "Mettre à Jour",
    remove: "Retirer",
    back: "Retour aux Patients",
    age: "Âge",
    years: "ans",

    // Common
    loading: "Chargement...",
    save: "Enregistrer",
    saving: "Enregistrement...",
    cancel: "Annuler",
    confirm: "Confirmer",
    search: "Rechercher",
    filter: "Filtrer",
    export: "Exporter",
    import: "Importer",
    noData: "Aucune donnée disponible",

    // Dashboard
    totalPatients: "Total des Patients",
    urgentCases: "Cas Urgents",
    activeTransfusions: "Transfusions Actives",
    scheduledTransfusions: "Transfusions Programmées",
    completedToday: "Complétées Aujourd'hui",

    // Scheduling
    scheduleTransfusion: "Programmer une Transfusion",
    regular: "Régulier",
    urgent: "Urgent",
    scheduledForTomorrow: "Programmé pour demain à 9h00",
    scheduledForToday: "Programmé pour aujourd'hui au prochain créneau disponible",
    selectDate: "Sélectionner la Date",
    selectTime: "Sélectionner l'Heure",
    selectType: "Sélectionner le Type",

    // Forms
    firstName: "Prénom",
    lastName: "Nom",
    email: "E-mail",
    phone: "Téléphone",
    address: "Adresse",
    dateOfBirth: "Date de Naissance",
    gender: "Genre",
    bloodGroup: "Groupe Sanguin",
    rhFactor: "Facteur RH",
    note: "Remarque",
    notes: "Remarques",
    reason: "Raison",
    status: "Statut",

    // Status
    pending: "En attente",
    inProgress: "En Cours",
    cancelled: "Annulé",
    successful: "Réussi",
    failed: "Échoué",

    // Settings
    language: "Langue",
    selectLanguage: "Sélectionner la Langue",
    theme: "Thème",
    darkMode: "Mode Sombre",
    notifications: "Notifications",
    soundEnabled: "Son Activé",
    emailNotifications: "Notifications par E-mail",
    updateProfile: "Mettre à Jour le Profil",
    changePassword: "Changer le Mot de Passe",
    logout: "Déconnexion",
    myProfile: "Mon Profil",
    profileSettings: "Paramètres du Profil",

    // Analytics
    totalTransfusions: "Total des Transfusions",
    numberOfBags: "Nombre de Poches",
    avgHemoglobin: "Hémoglobine Moyenne",
    criticalCases: "Cas Critiques",
    activePatients: "Patients Actifs",
    transfusionsToday: "Transfusions Aujourd'hui",
    rarePhenotypes: "Phénotypes Rares",
    dominantBloodType: "Groupe Sanguin Dominant",
    chartsAndTrends: "Graphiques et Tendances",
    transfusionDataVisualization: "Représentation visuelle des données de transfusion",
    transfusionsAndBags: "Transfusions et Poches Sanguines",
    transfusionsScheduledVsCompleted: "Transfusions programmées vs complétées avec nombre de poches",
    bloodGroupsAndHemoglobin: "Groupes Sanguins et Hémoglobine",
    hemoglobinDistribution: "Distribution avec taux d'hémoglobine moyen",
    prioritiesAndBags: "Priorités et Poches Sanguines",
    distributionByPriority: "Distribution par priorité avec nombre de poches",
    monthlyTrends: "Tendances Mensuelles",
    transfusionByMonth: "Transfusions par mois avec progression",
    vsLastWeek: "vs semaine précédente",
    vsLastPeriod: "vs période précédente",
    bagPerTransfusion: "poches par transfusion",
    range: "Plage",
    newPatients: "nouveaux patients",
    patients: "patients",
    completed: "complétées",
    data: "Données",
    chart: "Graphique",
    no: "Aucune",

    // Transfusions
    noTransfusionScheduled: "Aucune transfusion programmée",
    noBloodTransfusionsScheduled: "Il n'y a pas de transfusions sanguines programmées pour demain",
    noBloodTransfusionsScheduledToday: "Il n'y a pas de transfusions sanguines programmées pour aujourd'hui",
    print: "Imprimer",
    dailyTransfusionReport: "Rapport Quotidien des Transfusions",
    transfusionSchedule: "Programme des Transfusions Sanguines",
    confirmDeleteTransfusion: "Êtes-vous sûr de vouloir supprimer cette transfusion?",
    deleted: "Supprimé",
    transfusionDeleted: "Transfusion supprimée avec succès",
    deletionFailed: "Échec de la suppression de la transfusion",

    // Patient Management
    patientRecords: "Dossiers des Patients",
    manageAllPatients: "Gérer tous les dossiers des patients et l'historique des transfusions",
    patientFound: "Aucun patient trouvé",
    tryAdjustingSearch: "Essayez d'ajuster vos critères de recherche ou vos filtres.",
    addNewPatient: "Ajouter un Nouveau Patient",
    errorLoadingPatients: "Erreur lors du chargement des patients",
    failedLoadingPatients: "Une erreur s'est produite lors du chargement des données des patients. Veuillez réessayer.",
    retry: "Réessayer",
    patientInformation: "Informations du Patient",
    contactInformation: "Informations de Contact",
    contactDetailsDescription: "Mettez à jour les coordonnées du patient et les informations d'urgence.",
    medicalInformation: "Informations Médicales",
    medicalDetailsDescription: "Mettez à jour le groupe sanguin du patient, les antécédents médicaux et les détails de transfusion.",
    positive: "Positif",
    negative: "Négatif",
    selectAdmissionDate: "Sélectionner la date d'admission",
    selectLastTransfusionDate: "Sélectionner la date de la dernière transfusion",
    patientAttributes: "Attributs du Patient",
    selectPatientCategory: "Sélectionner la catégorie du patient",
    pathology: "Pathologie",
    alloImmunisationStatus: "Statut d'Allo-immunisation",
    transfusionHistory: "Historique des Transfusions",
    patientActive: "Patient Actif",
    neverTransfused: "Jamais transfusé",
    notProvided: "Non fournie",
    notAvailable: "N/A",
    editPersonalInfo: "Modifier vos informations personnelles",
    bloodType: "Groupe Sanguin",
    weight: "Poids (kg)",
    height: "Taille (cm)",
    hemoglobinLevel: "Niveau d'Hémoglobine (g/dL)",
    admissionDate: "Date d'Admission",
    lastTransfusionDate: "Dernière Date de Transfusion",
    medicalHistory: "Antécédents Médicaux",
    emergencyContact: "Contact d'Urgence",
    emergencyPhone: "Téléphone d'Urgence",
    male: "Masculin",
    female: "Féminin",
    hyperRegime: "HyperRégime",
    polyTransfused: "PolyTransfusés",
    exchanges: "Échanges",
    occasionalExchanges: "Échanges Occasionnels",
    patientCategory: "Catégorie de Patient",
    selectPatientCategory: "Sélectionner la catégorie du patient",
    pathologyPlaceholder: "Saisir la pathologie du patient...",
    alloImmunisationStatusPlaceholder: "Saisir le statut d'allo-immunisation...",
    medicalHistoryAndNotes: "Antécédents Médicaux et Notes",
    medicalHistoryPlaceholder: "Saisir les antécédents médicaux pertinents, allergies, médicaments ou notes spéciales...",
    allPatients: "Tous les Patients",
    addPatient: "Ajouter un Patient",
    editPatient: "Modifier un Patient",
    savePatient: "Enregistrer le Patient",
    deletePatientConfirm: "Êtes-vous sûr de vouloir supprimer ce patient? Cette action ne peut pas être annulée.",
    deletePatient: "Supprimer le Patient",
    patientDeleted: "Patient supprimé avec succès",
    patientAdded: "Patient ajouté avec succès",
    patientAddedMessage: "Le nouveau patient a été enregistré avec succès.",
    patientUpdated: "Patient mis à jour avec succès",
    patientUpdatedMessage: "Les informations du patient ont été mises à jour avec succès.",
    failedToSavePatient: "Échec de l'enregistrement du patient. Veuillez réessayer.",
    validationError: "Erreur de Validation",
    selectGender: "Veuillez sélectionner un sexe.",
    selectCategory: "Veuillez sélectionner une catégorie.",
    selectBloodType: "Veuillez sélectionner un groupe sanguin.",
    selectPhenotype: "Veuillez sélectionner un phénotype.",
    scheduleTransfusionNow: "Programmer une Transfusion",
    scheduleRegular: "Programmer Régulier",
    scheduleUrgent: "Programmer Urgent",
    scheduleForToday: "Programmé pour aujourd'hui à 14h00",
    scheduleForTomorrow: "Programmé pour demain à 09h00",
    failedScheduling: "Échec de la programmation de la transfusion. Veuillez réessayer.",
    daysElapsed: "Jours Écoulés",
    searchPatients: "Rechercher des Patients",
    bloodTypeFilter: "Groupe Sanguin",
    phenotypeFilter: "Phénotype",
    actions: "Actions",
    viewDetails: "Voir les Détails",
    editDetails: "Modifier les Détails",

    // History and Transfusion Pages
    addPatientForDay: "Ajouter un patient pour ce jour",
    addTransfusion: "Ajouter une Transfusion",
    selectPatient: "Sélectionner un patient",
    priority: "Priorité",
    bags: "Poches",
    hdist: "H.dist",
    hreceived: "H.reçu",
    noTransfusionFound: "Aucune transfusion trouvée.",
    phenotype: "Phénotype",
    hasF: "F",
    hasC: "C",
    hasL: "L",
    presence: "Présence",
    absent: "Absent",
    present: "Présent",
    patient: "Patient",
    don: "Don",
    normale: "normale",
    urgente: "urgente",
    chuAnnaba: "CHU ANNABA SERVICE D'HÉMOBIOLOGIE ET TRANSFUSION SANGUINE",
    chefDeService: "CHEF DE SERVICE PR. BROUK HACENE",
    patientNotFound: "Patient non trouvé",
    noPastSchedules: "Aucun programme antérieur.",
    date: "Date",
    modifierHbPostTransfusion: "Modifier Hb Post Transfusion",
    hbPostTransfusion: "Hb Post Transfusion",
    misAJour: "Mis à jour",
    hbfUpdated: "HbF mis à jour.",
    hbPostTransfusionOf: "Hb Post Transfusion du",
    previous: "Précédent",
    next: "Suivant",
    showingPatients: "Affichage de {count} patients",
    searchByPatientName: "Rechercher par nom du patient...",
    showingTransfusionsMatching: 'Affichage de {count} sur {total} transfusions correspondant à "{query}"',
    showingTransfusionsScheduled: "Affichage de {count} transfusions programmées pour aujourd'hui",
    transfusionsSummary: "({completed} terminées, {pending} en attente)",
    totalOrders: "{count} commandes au total",
    deliveredOrders: "({count} commandes distribuées)",
    urgentTransfusions: "Transfusions urgentes",
    markCompleted: "Marquer terminé",
    unmarkCompleted: "Annuler",
    patientRecordsReport: "BloodCare - Rapport des Dossiers Patients",
    hbPT: "Hb PT",
    yesLabel: "Oui",
    noLabel: "Non",
    managementSystem: "Système de Gestion",
    closeNav: "Fermer le menu de navigation",
    openNav: "Ouvrir le menu de navigation",
    expandSidebar: "Développer la barre latérale",
    collapseSidebar: "Réduire la barre latérale",
    editTransfusion: "Modifier la Transfusion",
    transfusionDetails: "Détails de la Transfusion",
    updateTransfusionDetailsDescription: "Mettre à jour les détails de la transfusion du patient et les informations sur les unités de sang.",
    transfusionUpdated: "Transfusion mise à jour avec succès.",
    transfusionUpdatedDescription: "Les informations de la transfusion ont été mises à jour avec succès.",
    deletePatientConfirmTitle: "Êtes-vous absolument sûr ?",
    deletePatientConfirmDescription: "Cette action est irréversible. Elle supprimera définitivement le dossier du patient et toutes les données associées.",
    patientDeletedTitle: "Patient supprimé",
    patientDeletedDescription: "Le patient a été supprimé avec succès.",
    deletePatientFailed: "Impossible de supprimer le patient. Veuillez réessayer.",
    deletePatientTooltip: "Supprimer le patient",
    deleting: "Suppression...",
    allOrders: "commandes au total",
    ordersDelivered: "commandes distribuées",
    transfusionsScheduledForToday: "transfusions programmées pour aujourd'hui",

    // Messages
    success: "Succès",
    error: "Erreur",
    warning: "Avertissement",
    info: "Information",
    confirmDelete: "Êtes-vous sûr de vouloir supprimer ceci?",
    confirmLogout: "Êtes-vous sûr de vouloir vous déconnecter?",
    invalidInput: "Entrée invalide",
    required: "Veuillez remplir tous les champs obligatoires marqués d'un astérisque (*)",
  },
  ar: {
    // Navigation
    dashboard: "لوحة التحكم",
    patients: "المرضى",
    analytics: "التحليلات",
    settings: "الإعدادات",
    todayTransfusions: "نقل الدم اليوم",
    tomorrowTransfusions: "نقل الدم غدًا",
    history: "السجل",
    reports: "التقارير",
    analyse: "التحليل",

    // Patient Table Headers
    nomEtPrenom: "الاسم",
    gp: "GP",
    ph: "PH",
    f: "F",
    c: "C",
    l: "L",
    derniereT: "آخر نقل",
    prochaineT: "نقل قادم",
    jecoulés: "أيام مضت",
    renseignements: "الإجراءات",
    bloodType: "فصيلة الدم",
    lastTransfusion: "آخر نقل دم",
    nextTransfusion: "نقل الدم القادم",

    // Actions
    view: "عرض",
    edit: "تعديل",
    delete: "حذف",
    schedule: "جدولة",
    done: "تم",
    completed: "مكتمل",
    markAsDone: "وضع علامة كمكتمل",
    add: "إضافة",
    create: "إنشاء",
    update: "تحديث",
    remove: "إزالة",
    back: "العودة إلى المرضى",
    age: "العمر",
    years: "سنة",

    // Common
    loading: "جاري التحميل...",
    save: "حفظ",
    saving: "جار الحفظ...",
    cancel: "إلغاء",
    confirm: "تأكيد",
    search: "البحث",
    filter: "تصفية",
    export: "تصدير",
    import: "استيراد",
    noData: "لا توجد بيانات",

    // Dashboard
    totalPatients: "إجمالي المرضى",
    urgentCases: "حالات طارئة",
    activeTransfusions: "عمليات نقل نشطة",
    scheduledTransfusions: "عمليات نقل مجدولة",
    completedToday: "مكتملة اليوم",

    // Scheduling
    scheduleTransfusion: "جدولة نقل دم",
    regular: "منتظم",
    urgent: "طارئ",
    scheduledForTomorrow: "مجدول لغدًا الساعة 9:00 صباحًا",
    scheduledForToday: "مجدول لليوم في أقرب وقت متاح",
    selectDate: "اختر التاريخ",
    selectTime: "اختر الوقت",
    selectType: "اختر النوع",

    // Forms
    firstName: "الاسم الأول",
    lastName: "الاسم الأخير",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    address: "العنوان",
    dateOfBirth: "تاريخ الميلاد",
    gender: "الجنس",
    bloodGroup: "فصيلة الدم",
    rhFactor: "عامل RH",
    note: "ملا��ظة",
    notes: "ملاحظات",
    reason: "السبب",
    status: "الحالة",

    // Status
    pending: "قيد الانتظار",
    inProgress: "قيد التنفيذ",
    cancelled: "ملغى",
    successful: "نجح",
    failed: "فشل",

    // Settings
    language: "اللغة",
    selectLanguage: "اختر اللغة",
    theme: "المظهر",
    darkMode: "الوضع الداكن",
    notifications: "الإخطارات",
    soundEnabled: "الصوت مفعل",
    emailNotifications: "إخطارات البريد الإلكتروني",
    updateProfile: "تحديث الملف الشخصي",
    changePassword: "تغيير كلمة المرور",
    logout: "تسجيل الخروج",
    myProfile: "ملفي الشخصي",
    profileSettings: "إعدادات الملف الشخصي",

    // Analytics
    totalTransfusions: "إجمالي عمليات النقل",
    numberOfBags: "عدد الأكياس",
    avgHemoglobin: "متوسط الهيموجلوبين",
    criticalCases: "حالات حرجة",
    activePatients: "المرضى النشطون",
    transfusionsToday: "عمليات النقل اليوم",
    rarePhenotypes: "الأنماط الظاهرية النادرة",
    dominantBloodType: "فصيلة الدم السائدة",
    chartsAndTrends: "الرسوم البيانية والاتجاهات",
    transfusionDataVisualization: "تصور مرئي لبيانات النقل",
    transfusionsAndBags: "عمليات النقل والأكياس",
    transfusionsScheduledVsCompleted: "عمليات النقل المجدولة مقابل المكتملة مع عدد الأكياس",
    bloodGroupsAndHemoglobin: "فصائل الدم والهيموجلوبين",
    hemoglobinDistribution: "التوزيع مع متوسط مستوى الهيموجلوبين",
    prioritiesAndBags: "الأولويات والأكياس",
    distributionByPriority: "التوزيع حسب الأولوية مع عدد الأكياس",
    monthlyTrends: "الاتجاهات الشهرية",
    transfusionByMonth: "عمليات النقل حسب الشهر مع التقدم",
    vsLastWeek: "مقابل الأسبوع الماضي",
    vsLastPeriod: "مقابل الفترة السابقة",
    bagPerTransfusion: "أكياس لكل نقل",
    range: "النطاق",
    newPatients: "مرضى جدد",
    patients: "مرضى",
    completed: "مكتملة",
    data: "البيانات",
    chart: "مخطط",
    no: "لا توجد",

    // Transfusions
    noTransfusionScheduled: "لا توجد نقل مجدولة",
    noBloodTransfusionsScheduled: "لا توجد عمليات نقل دم مجدولة لغد",
    noBloodTransfusionsScheduledToday: "لا توجد عمليات نقل دم مجدولة لليوم",
    print: "طباعة",
    dailyTransfusionReport: "التقرير اليومي للنقل",
    transfusionSchedule: "جدول نقل الدم",
    confirmDeleteTransfusion: "هل أنت متأكد من رغبتك في حذف هذه النقل؟",
    deleted: "تم الحذف",
    transfusionDeleted: "تم حذف النقل بنجاح",
    deletionFailed: "فشل حذف النقل",

    // Patient Management
    patientRecords: "سجلات المرضى",
    manageAllPatients: "إدارة جميع سجلات المرضى وسجل النقل",
    patientFound: "لم يتم العثور على أي مريض",
    tryAdjustingSearch: "حاول تعديل معايير البحث أو المرشحات الخاصة بك.",
    addNewPatient: "إضافة مريض جديد",
    errorLoadingPatients: "خطأ في تحميل المرضى",
    failedLoadingPatients: "حدث خطأ أثناء تحميل بيانات المريض. يرجى المحاولة مرة أخرى.",
    retry: "إعادة محاولة",
    patientInformation: "معلومات المريض",
    contactInformation: "معلومات الاتصال",
    contactDetailsDescription: "قم بتحديث تفاصيل الاتصال بالمريض ومعلومات الطوارئ.",
    medicalInformation: "معلومات طبية",
    medicalDetailsDescription: "قم بتحديث فصيلة دم المريض، التاريخ الطبي، وتفاصيل النقل.",
    positive: "إيجابي",
    negative: "سلبي",
    selectAdmissionDate: "اختر تاريخ الدخول",
    selectLastTransfusionDate: "اختر تاريخ آخر نقل دم",
    patientAttributes: "سمات المريض",
    selectPatientCategory: "اختر فئة المريض",
    pathology: "الاعتلال",
    alloImmunisationStatus: "حالة التحسس المناعي",
    transfusionHistory: "سجل عمليات نقل الدم",
    patientActive: "مريض نشط",
    neverTransfused: "لم يتم نقل دم",
    notProvided: "غير مقدم",
    notAvailable: "غير متوفر",
    editPersonalInfo: "تعديل معلوماتك الشخصية",
    bloodType: "فصيلة الدم",
    weight: "الوزن (كجم)",
    height: "الارتفاع (سم)",
    hemoglobinLevel: "مستوى الهيموجلوبين (g/dL)",
    admissionDate: "تاريخ الدخول",
    lastTransfusionDate: "آخر تاريخ نقل دم",
    medicalHistory: "السجل الطبي",
    emergencyContact: "جهة الاتصال في حالات الطوارئ",
    emergencyPhone: "هاتف الطوارئ",
    male: "ذكر",
    female: "أنثى",
    hyperRegime: "النظام الفائق",
    polyTransfused: "متعدد النقل",
    exchanges: "التبادلات",
    occasionalExchanges: "التبادلات العرضية",
    patientCategory: "فئة المريض",
    selectPatientCategory: "اختر فئة المريض",
    pathologyPlaceholder: "أدخل تفاصيل الاعتلال للمريض...",
    alloImmunisationStatusPlaceholder: "أدخل حالة التحسس المناعي...",
    medicalHistoryAndNotes: "السجل الطبي والملاحظات",
    medicalHistoryPlaceholder: "أدخل التاريخ الطبي ذي الصلة، الحساسية، الأدوية، أو الملاحظات الخاصة...",
    allPatients: "جميع المرضى",
    addPatient: "إضافة مريض",
    editPatient: "تعديل المريض",
    savePatient: "حفظ المريض",
    deletePatientConfirm: "هل أنت متأكد من رغبتك في حذف هذا المريض؟ لا يمكن التراجع عن هذا الإجراء.",
    deletePatient: "حذف المريض",
    patientDeleted: "تم حذف المريض بنجاح",
    patientAdded: "تمت إضافة المريض بنجاح",
    patientAddedMessage: "تمت إضافة المريض الجديد بنجاح.",
    patientUpdated: "تم تحديث المريض بنجاح",
    patientUpdatedMessage: "تم تحديث معلومات المريض بنجاح.",
    failedToSavePatient: "فشل حفظ تفاصيل المريض. يرجى المحاولة مرة أخرى.",
    validationError: "خطأ في التحقق",
    selectGender: "يرجى اختيار جنس.",
    selectCategory: "يرجى اختيار فئة.",
    selectBloodType: "يرجى اختيار فصيلة دم.",
    selectPhenotype: "يرجى اختيار نمط ظاهري.",
    scheduleTransfusionNow: "جدولة نقل الآن",
    scheduleRegular: "جدولة عادية",
    scheduleUrgent: "جدولة طارئة",
    scheduleForToday: "مجدول لليوم الساعة 2:00 مساءً",
    scheduleForTomorrow: "مجدول لغدًا الساعة 9:00 صباحًا",
    failedScheduling: "فشل جدولة النقل. يرجى المحاولة مرة أخرى.",
    daysElapsed: "الأيام المنقضية",
    searchPatients: "البحث عن المرضى",
    bloodTypeFilter: "فصيلة الدم",
    phenotypeFilter: "النمط الظاهري",
    actions: "الإجراءات",
    viewDetails: "عرض التفاصيل",
    editDetails: "تعديل التفاصيل",

    // History and Transfusion Pages
    addPatientForDay: "إضافة مريض لهذا اليوم",
    addTransfusion: "إضافة نقل دم",
    selectPatient: "اختر مريضًا",
    priority: "الأولوية",
    bags: "الأكياس",
    hdist: "H.dist",
    hreceived: "H.مستقبل",
    noTransfusionFound: "لم يتم العثور على أي نقل دم.",
    phenotype: "النمط الظاهري",
    hasF: "F",
    hasC: "C",
    hasL: "L",
    presence: "الحضور",
    absent: "غائب",
    present: "حاضر",
    patient: "المريض",
    don: "تبرع",
    normale: "عادي",
    urgente: "عاجل",
    chuAnnaba: "مستشفى جامعة عنابة مصلحة علم الدم ونقل الدم",
    chefDeService: "رئيس المصلحة الأستاذ بروك حسن",
    patientNotFound: "المريض غير موجود",
    noPastSchedules: "لا توجد جداول نقل دم سابقة.",
    date: "التاريخ",
    modifierHbPostTransfusion: "تعديل الهيموجلوبين بعد نقل الدم",
    hbPostTransfusion: "الهيموجلوبين بعد نقل الدم",
    misAJour: "تم التحديث",
    hbfUpdated: "تم تحديث HbF بنجاح.",
    hbPostTransfusionOf: "الهيموجلوبين بعد نقل الدم لـ",
    previous: "السابق",
    next: "التالي",
    showingPatients: "عرض {count} من المرضى",
    searchByPatientName: "البحث باسم المريض...",
    showingTransfusionsMatching: 'عرض {count} من أصل {total} من عمليات نقل الدم المطابقة لـ "{query}"',
    showingTransfusionsScheduled: "عرض {count} من عمليات نقل الدم المجدولة لليوم",
    transfusionsSummary: "({completed} مكتملة، {pending} قيد الانتظار)",
    totalOrders: "إجمالي {count} طلبات",
    deliveredOrders: "({count} طلبات تم تسليمها)",
    urgentTransfusions: "عمليات نقل الدم العاجلة",
    markCompleted: "تحديد كمكتمل",
    unmarkCompleted: "إلغاء",
    patientRecordsReport: "BloodCare - تقرير سجلات المرضى",
    hbPT: "Hb PT",
    yesLabel: "نعم",
    noLabel: "لا",
    managementSystem: "نظام الإدارة",
    closeNav: "إغلاق قائمة التنقل",
    openNav: "فتح قائمة التنقل",
    expandSidebar: "توسيع الشريط الجانبي",
    collapseSidebar: "طي الشريط الجانبي",
    editTransfusion: "تعديل عملية نقل الدم",
    transfusionDetails: "تفاصيل عملية نقل الدم",
    updateTransfusionDetailsDescription: "تحديث تفاصيل نقل دم المريض ومعلومات وحدات الدم.",
    transfusionUpdated: "تم تحديث عملية نقل الدم بنجاح.",
    transfusionUpdatedDescription: "تم تحديث معلومات نقل الدم بنجاح.",
    deletePatientConfirmTitle: "هل أنت متأكد تمامًا؟",
    deletePatientConfirmDescription: "هذا الإجراء لا يمكن التراجع عنه. سيؤدي هذا إلى حذف سجل المريض وجميع البيانات المرتبطة به نهائيًا.",
    patientDeletedTitle: "تم حذف المريض",
    patientDeletedDescription: "تم حذف المريض بنجاح.",
    deletePatientFailed: "تعذر حذف المريض. يرجى المحاولة مرة أخرى.",
    deletePatientTooltip: "حذف المريض",
    deleting: "جاري الحذف...",
    allOrders: "إجمالي الطلبات",
    ordersDelivered: "الطلبات المسلمة",
    transfusionsScheduledForToday: "عمليات نقل الدم المجدولة لليوم",

    // Messages
    success: "نجح",
    error: "خطأ",
    warning: "تحذير",
    info: "معلومات",
    confirmDelete: "هل أنت متأكد من حذف هذا؟",
    confirmLogout: "هل أنت متأكد من تسجيل الخروج؟",
    invalidInput: "إدخال غير صالح",
    required: "يرجى ملء جميع الحقول الإلزامية المميزة بعلامة النجمة (*)",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    // Load language from localStorage
    const savedSettings = localStorage.getItem("systemSettings")
    if (savedSettings) {
      const settings = JSON.parse(savedSettings)
      if (settings.language) {
        setLanguage(settings.language)
        updateLanguageUI(settings.language)
      }
    }

    const handleLanguageChange = (event: CustomEvent) => {
      setLanguage(event.detail.language)
      updateLanguageUI(event.detail.language)
    }

    window.addEventListener("languageChanged", handleLanguageChange as EventListener)
    return () => {
      window.removeEventListener("languageChanged", handleLanguageChange as EventListener)
    }
  }, [])

  const updateLanguageUI = (lang: Language) => {
    document.documentElement.lang = lang
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr"
    document.documentElement.className = lang === "ar" ? "rtl" : "ltr"
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
