const { MongoClient } = require("mongodb")

const client = new MongoClient(process.env.MONGODB_URI || "mongodb://localhost:27017")
const dbName = "blood_donation_system"

async function seedDatabase() {
  try {
    await client.connect()
    const db = client.db(dbName)

    await db.collection("patients").deleteMany({})
    await db.collection("transfusions").deleteMany({})

    const samplePatients = 
    [
      {
        "firstName": "Asma",
        "lastName": "Kheireddine",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Amινα",
        "lastName": "Lounissi",
        "bloodType": "B+",
        "ph": "Cceek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Bochra",
        "lastName": "Lounissi",
        "bloodType": "B+",
        "ph": "Cceek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Meriem",
        "lastName": "Mansouri",
        "bloodType": "O+",
        "ph": "CcEek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Chaima",
        "lastName": "Merabet",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Nada",
        "lastName": "Merabet",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": true,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Amira",
        "lastName": "Mesbah",
        "bloodType": "AB-",
        "ph": "cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": true,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Chaima",
        "lastName": "Mokadem",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": true,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Asma",
        "lastName": "Mokhneche",
        "bloodType": "B+",
        "ph": "CcEek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Said",
        "lastName": "Mokhneche",
        "bloodType": "B+",
        "ph": "Cceek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Tahar",
        "lastName": "Saadi",
        "bloodType": "O+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Dellel",
        "lastName": "Saadna",
        "bloodType": "O+",
        "ph": "cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Fairouz",
        "lastName": "Souadnia",
        "bloodType": "O+",
        "ph": "cceek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Fatima",
        "lastName": "Zaidi",
        "bloodType": "AB+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Toufik",
        "lastName": "Belhaouassa",
        "bloodType": "O+",
        "ph": "cceek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Αυμεν",
        "lastName": "Saadoune",
        "bloodType": "A+",
        "ph": "CcEek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Yasmine",
        "lastName": "Hadad",
        "bloodType": "O+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Soulafa",
        "lastName": "Boulahraf",
        "bloodType": "O+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Meriem",
        "lastName": "Nerier",
        "bloodType": "O+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Kenza",
        "lastName": "Beghagha",
        "bloodType": "O+",
        "ph": "CcEek-",
        "hasF": false,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Nadia",
        "lastName": "Bouzidi",
        "bloodType": "B+",
        "ph": "cceek+",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Chiraz",
        "lastName": "Merah",
        "bloodType": "A+",
        "ph": "cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Haroun",
        "lastName": "Sedrati",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Nourelhouda",
        "lastName": "Guechi",
        "bloodType": "B+",
        "ph": "Cceek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Khaled",
        "lastName": "Khalfallah",
        "bloodType": "B+",
        "ph": "CcEek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Dorsaf",
        "lastName": "Laib",
        "bloodType": "A-",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Safa",
        "lastName": "Bensalem",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": true,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Rachedi",
        "lastName": "Othemane",
        "bloodType": "A+",
        "ph": "CCeek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Fatima",
        "lastName": "Hamadou",
        "bloodType": "B+",
        "ph": "CcEek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Rachid",
        "lastName": "Benramdane",
        "bloodType": "AB+",
        "ph": "cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Mohamed",
        "lastName": "Chergui",
        "bloodType": "AB+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Tasnim",
        "lastName": "Soualem",
        "bloodType": "O+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Chahrazed",
        "lastName": "Aroussi",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Anfel",
        "lastName": "Kesas",
        "bloodType": "O+",
        "ph": "ccEek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Youcef",
        "lastName": "Marouani",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Hibeterahμανε",
        "lastName": "Boughrara",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Youcef",
        "lastName": "Merouani",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Amira",
        "lastName": "Amari",
        "bloodType": "O+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Mounir",
        "lastName": "Babes",
        "bloodType": "O-",
        "ph": "cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Oumaima",
        "lastName": "Belhanachi",
        "bloodType": "A+",
        "ph": "cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Fethi",
        "lastName": "Benchabane",
        "bloodType": "AB+",
        "ph": "ccEek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Narimene",
        "lastName": "Benslimane",
        "bloodType": "A+",
        "ph": "CCeek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Chemseddine",
        "lastName": "Berrouki",
        "bloodType": "O-",
        "ph": "cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Rayane",
        "lastName": "Boudalia",
        "bloodType": "O+",
        "ph": "Cceek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Feriel",
        "lastName": "Boughrara",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Roubila",
        "lastName": "Bouneb",
        "bloodType": "O+",
        "ph": "CcEek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Chemseddine",
        "lastName": "Bouzid",
        "bloodType": "B+",
        "ph": "ccEek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Saloua",
        "lastName": "Chaib",
        "bloodType": "O+",
        "ph": "cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": true,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Sadek",
        "lastName": "Chara",
        "bloodType": "AB+",
        "ph": "CCeek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Meriem",
        "lastName": "Cheriet",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Halima",
        "lastName": "Dahmani",
        "bloodType": "A-",
        "ph": "cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Khaled",
        "lastName": "Djabali",
        "bloodType": "A+",
        "ph": "CcEek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Ghania",
        "lastName": "Djemoui",
        "bloodType": "B+",
        "ph": "CCeek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "A-Wadoud",
        "lastName": "Drici",
        "bloodType": "O+",
        "ph": "CCeek-",
        "hasF": true,
        "hasC": false,
        "hasL": true,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Riheb",
        "lastName": "Guediri",
        "bloodType": "B+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Warda",
        "lastName": "Sehailia",
        "bloodType": "O+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Nadjette",
        "lastName": "Mansouri",
        "bloodType": "B+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Hamza",
        "lastName": "Hami",
        "bloodType": "A+",
        "ph": "cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Ali",
        "lastName": "Leday",
        "bloodType": "O+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Wissam",
        "lastName": "Benyahia",
        "bloodType": "O+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Amir",
        "lastName": "Sakri",
        "bloodType": "B+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Alla",
        "lastName": "Khobaiza",
        "bloodType": "A+",
        "ph": "cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Mouhamed",
        "lastName": "Belhait",
        "bloodType": "A+",
        "ph": "ccEek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Oussama",
        "lastName": "Khanfoussi",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Hanane",
        "lastName": "Lemtayache",
        "bloodType": "O+",
        "ph": "cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Ibtihel",
        "lastName": "Benchana",
        "bloodType": "O+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Ahmed",
        "lastName": "Hafiane",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Fatma",
        "lastName": "Chabbi",
        "bloodType": "O+",
        "ph": "CcEek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Achraf",
        "lastName": "Nasri",
        "bloodType": "O+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Khaled",
        "lastName": "Saci",
        "bloodType": "B+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "PolyTransfuses",
        "createdAt": "2025-06-16T00:10:46.888044",
        "updatedAt": "2025-06-16T00:10:46.888044"
      },
      {
        "firstName": "Azzeddine",
        "lastName": "Doghmane",
        "bloodType": "B+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": true,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227486",
        "updatedAt": "2025-06-16T00:06:59.227506"
      },
      {
        "firstName": "Doha",
        "lastName": "Drici",
        "bloodType": "A+",
        "ph": "ccEek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227515",
        "updatedAt": "2025-06-16T00:06:59.227517"
      },
      {
        "firstName": "Imad",
        "lastName": "Fardjallah",
        "bloodType": "AB+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227522",
        "updatedAt": "2025-06-16T00:06:59.227524"
      },
      {
        "firstName": "Roukia",
        "lastName": "Khalfallah",
        "bloodType": "AB-",
        "ph": "cceek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227529",
        "updatedAt": "2025-06-16T00:06:59.227531"
      },
      {
        "firstName": "May Dorsaf",
        "lastName": "Merah",
        "bloodType": "O-",
        "ph": "cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227535",
        "updatedAt": "2025-06-16T00:06:59.227537"
      },
      {
        "firstName": "Wail",
        "lastName": "Mihoubi",
        "bloodType": "O+",
        "ph": "CcEek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227543",
        "updatedAt": "2025-06-16T00:06:59.227545"
      },
      {
        "firstName": "Maroua",
        "lastName": "Sebti",
        "bloodType": "A+",
        "ph": "CcEek-",
        "hasF": true,
        "hasC": false,
        "hasL": true,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227550",
        "updatedAt": "2025-06-16T00:06:59.227552"
      },
      {
        "firstName": "Raouia",
        "lastName": "Merah",
        "bloodType": "A-",
        "ph": "cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": true,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227555",
        "updatedAt": "2025-06-16T00:06:59.227557"
      },
      {
        "firstName": "Oussama",
        "lastName": "Chaouche",
        "bloodType": "A+",
        "ph": "CcEek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227562",
        "updatedAt": "2025-06-16T00:06:59.227564"
      },
      {
        "firstName": "Khirreddine",
        "lastName": "Khalfallah",
        "bloodType": "A+",
        "ph": "CcEek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227567",
        "updatedAt": "2025-06-16T00:06:59.227569"
      },
      {
        "firstName": "Chaima",
        "lastName": "Kouadri",
        "bloodType": "B+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": true,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227573",
        "updatedAt": "2025-06-16T00:06:59.227574"
      },
      {
        "firstName": "Ali Bey",
        "lastName": "Touaref",
        "bloodType": "A-",
        "ph": "cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227578",
        "updatedAt": "2025-06-16T00:06:59.227580"
      },
      {
        "firstName": "Haroune",
        "lastName": "Berdjam",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227583",
        "updatedAt": "2025-06-16T00:06:59.227585"
      },
      {
        "firstName": "Soulef",
        "lastName": "Guidoum",
        "bloodType": "O+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227588",
        "updatedAt": "2025-06-16T00:06:59.227590"
      },
      {
        "firstName": "Abdelkader",
        "lastName": "Djali",
        "bloodType": "O-",
        "ph": "Cceek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227594",
        "updatedAt": "2025-06-16T00:06:59.227596"
      },
      {
        "firstName": "Nour Elislam",
        "lastName": "Tabia",
        "bloodType": "O+",
        "ph": "ccEek-",
        "hasF": true,
        "hasC": false,
        "hasL": true,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227599",
        "updatedAt": "2025-06-16T00:06:59.227601"
      },
      {
        "firstName": "Ishak",
        "lastName": "Merdaci",
        "bloodType": "O+",
        "ph": "ccEek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227605",
        "updatedAt": "2025-06-16T00:06:59.227607"
      },
      {
        "firstName": "Amine",
        "lastName": "Berima",
        "bloodType": "B+",
        "ph": "CcEek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227611",
        "updatedAt": "2025-06-16T00:06:59.227612"
      },
      {
        "firstName": "Billel",
        "lastName": "Berima",
        "bloodType": "B+",
        "ph": "CCeek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227616",
        "updatedAt": "2025-06-16T00:06:59.227620"
      },
      {
        "firstName": "Nada Malak",
        "lastName": "Touaref",
        "bloodType": "A+",
        "ph": "CCeek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227623",
        "updatedAt": "2025-06-16T00:06:59.227625"
      },
      {
        "firstName": "Ilies",
        "lastName": "Fradj",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227628",
        "updatedAt": "2025-06-16T00:06:59.227630"
      },
      {
        "firstName": "Med Amine",
        "lastName": "Benmakhlouf",
        "bloodType": "O+",
        "ph": "CCeek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227634",
        "updatedAt": "2025-06-16T00:06:59.227635"
      },
      {
        "firstName": "Soumya",
        "lastName": "Aissaoui",
        "bloodType": "O+",
        "ph": "CcEek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227639",
        "updatedAt": "2025-06-16T00:06:59.227641"
      },
      {
        "firstName": "Fatma Zohra",
        "lastName": "Refes",
        "bloodType": "O+",
        "ph": "CcEek-",
        "hasF": true,
        "hasC": false,
        "hasL": true,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227644",
        "updatedAt": "2025-06-16T00:06:59.227646"
      },
      {
        "firstName": "Adem",
        "lastName": "Belli",
        "bloodType": "B-",
        "ph": "cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227649",
        "updatedAt": "2025-06-16T00:06:59.227651"
      },
      {
        "firstName": "Djaber",
        "lastName": "Boutaba",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": false,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227655",
        "updatedAt": "2025-06-16T00:06:59.227656"
      },
      {
        "firstName": "Kaouther",
        "lastName": "Khalfa",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": true,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227661",
        "updatedAt": "2025-06-16T00:06:59.227663"
      },
      {
        "firstName": "Islem",
        "lastName": "Bouchelaghem",
        "bloodType": "A+",
        "ph": "cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227667",
        "updatedAt": "2025-06-16T00:06:59.227668"
      },
      {
        "firstName": "Bouchra",
        "lastName": "Amri",
        "bloodType": "O-",
        "ph": "cceek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227672",
        "updatedAt": "2025-06-16T00:06:59.227673"
      },
      {
        "firstName": "Mohamed",
        "lastName": "Bouchoucha",
        "bloodType": "B+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227677",
        "updatedAt": "2025-06-16T00:06:59.227679"
      },
      {
        "firstName": "Abd El Malek",
        "lastName": "Briki",
        "bloodType": "A+",
        "ph": "cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227682",
        "updatedAt": "2025-06-16T00:06:59.227684"
      },
      {
        "firstName": "Yaakoub",
        "lastName": "Merdaci",
        "bloodType": "O+",
        "ph": "ccEek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227687",
        "updatedAt": "2025-06-16T00:06:59.227689"
      },
      {
        "firstName": "Mohammed",
        "lastName": "Ksouri",
        "bloodType": "B+",
        "ph": "CCeek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227692",
        "updatedAt": "2025-06-16T00:06:59.227694"
      },
      {
        "firstName": "Nesrine",
        "lastName": "Metlaqui",
        "bloodType": "O+",
        "ph": "ccEek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227698",
        "updatedAt": "2025-06-16T00:06:59.227699"
      },
      {
        "firstName": "Hamza",
        "lastName": "Bedoud",
        "bloodType": "O+",
        "ph": "cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227703",
        "updatedAt": "2025-06-16T00:06:59.227704"
      },
      {
        "firstName": "Habiba",
        "lastName": "Mansouri",
        "bloodType": "B+",
        "ph": "CcEek+",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227708",
        "updatedAt": "2025-06-16T00:06:59.227709"
      },
      {
        "firstName": "Feriel",
        "lastName": "Gasmi",
        "bloodType": "A+",
        "ph": "cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "HyperRegime",
        "createdAt": "2025-06-16T00:06:59.227714",
        "updatedAt": "2025-06-16T00:06:59.227716"
      },
      {
        "firstName": "Hayette",
        "lastName": "Amiri",
        "bloodType": "AB+",
        "ph": "CCeek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265468",
        "updatedAt": "2025-06-15T23:58:53.265488"
      },
      {
        "firstName": "Hacene",
        "lastName": "Aquadi",
        "bloodType": "B+",
        "ph": "CCeek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265497",
        "updatedAt": "2025-06-15T23:58:53.265500"
      },
      {
        "firstName": "Cherif",
        "lastName": "Arabi",
        "bloodType": "B-",
        "ph": "cceek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265505",
        "updatedAt": "2025-06-15T23:58:53.265507"
      },
      {
        "firstName": "Soufiane",
        "lastName": "Berrek",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": true,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265512",
        "updatedAt": "2025-06-15T23:58:53.265514"
      },
      {
        "firstName": "Zakaria",
        "lastName": "Boudebza",
        "bloodType": "O+",
        "ph": "cceek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265519",
        "updatedAt": "2025-06-15T23:58:53.265521"
      },
      {
        "firstName": "Mabrouk",
        "lastName": "Bounouala",
        "bloodType": "O-",
        "ph": "cceek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265525",
        "updatedAt": "2025-06-15T23:58:53.265527"
      },
      {
        "firstName": "Zohra",
        "lastName": "Chabbi",
        "bloodType": "B+",
        "ph": "CcEek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265534",
        "updatedAt": "2025-06-15T23:58:53.265535"
      },
      {
        "firstName": "Aya",
        "lastName": "Hadidi",
        "bloodType": "O+",
        "ph": "Cceek+",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265540",
        "updatedAt": "2025-06-15T23:58:53.265541"
      },
      {
        "firstName": "Hana",
        "lastName": "Hadidi",
        "bloodType": "B+",
        "ph": "cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": true,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265545",
        "updatedAt": "2025-06-15T23:58:53.265547"
      },
      {
        "firstName": "Chaima",
        "lastName": "Kettache",
        "bloodType": "O+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265551",
        "updatedAt": "2025-06-15T23:58:53.265553"
      },
      {
        "firstName": "Reda",
        "lastName": "Lounis",
        "bloodType": "AB+",
        "ph": "Cceek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265557",
        "updatedAt": "2025-06-15T23:58:53.265559"
      },
      {
        "firstName": "Houssemeddine",
        "lastName": "Mechouk",
        "bloodType": "O+",
        "ph": "cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265563",
        "updatedAt": "2025-06-15T23:58:53.265565"
      },
      {
        "firstName": "Rania",
        "lastName": "Hamdane",
        "bloodType": "O+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265570",
        "updatedAt": "2025-06-15T23:58:53.265572"
      },
      {
        "firstName": "Iles",
        "lastName": "Gouri",
        "bloodType": "O+",
        "ph": "CcEek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265576",
        "updatedAt": "2025-06-15T23:58:53.265578"
      },
      {
        "firstName": "Hassina",
        "lastName": "Bouaza",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265582",
        "updatedAt": "2025-06-15T23:58:53.265584"
      },
      {
        "firstName": "Zohra",
        "lastName": "Bahroun",
        "bloodType": "O+",
        "ph": "CCeek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265587",
        "updatedAt": "2025-06-15T23:58:53.265589"
      },
      {
        "firstName": "Wissem",
        "lastName": "Laarid",
        "bloodType": "B+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265594",
        "updatedAt": "2025-06-15T23:58:53.265596"
      },
      {
        "firstName": "Hocine",
        "lastName": "Blida",
        "bloodType": "A+",
        "ph": "cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265600",
        "updatedAt": "2025-06-15T23:58:53.265602"
      },
      {
        "firstName": "Zoubir",
        "lastName": "Merakha",
        "bloodType": "O-",
        "ph": "cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265606",
        "updatedAt": "2025-06-15T23:58:53.265609"
      },
      {
        "firstName": "Mounia",
        "lastName": "Djemaa",
        "bloodType": "A+",
        "ph": "CCeek-",
        "hasF": false,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265613",
        "updatedAt": "2025-06-15T23:58:53.265615"
      },
      {
        "firstName": "Safa",
        "lastName": "Boutchiche",
        "bloodType": "B+",
        "ph": "Cceek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265619",
        "updatedAt": "2025-06-15T23:58:53.265621"
      },
      {
        "firstName": "Mahieddine",
        "lastName": "Bouderbela",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265625",
        "updatedAt": "2025-06-15T23:58:53.265627"
      },
      {
        "firstName": "Mouna",
        "lastName": "Haciri",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265632",
        "updatedAt": "2025-06-15T23:58:53.265634"
      },
      {
        "firstName": "Louai",
        "lastName": "Laribi",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": true,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265638",
        "updatedAt": "2025-06-15T23:58:53.265639"
      },
      {
        "firstName": "Hamza",
        "lastName": "Zaim",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265643",
        "updatedAt": "2025-06-15T23:58:53.265645"
      },
      {
        "firstName": "Warda",
        "lastName": "Khadem",
        "bloodType": "B+",
        "ph": "CCeek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265649",
        "updatedAt": "2025-06-15T23:58:53.265651"
      },
      {
        "firstName": "Khadidja",
        "lastName": "Khalfa",
        "bloodType": "A+",
        "ph": "ccEek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265656",
        "updatedAt": "2025-06-15T23:58:53.265658"
      },
      {
        "firstName": "Jam",
        "lastName": "Berd",
        "bloodType": "O+",
        "ph": "CcEek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265662",
        "updatedAt": "2025-06-15T23:58:53.265664"
      },
      {
        "firstName": "Serine",
        "lastName": "Zitouni",
        "bloodType": "O+",
        "ph": "CcEek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265668",
        "updatedAt": "2025-06-15T23:58:53.265669"
      },
      {
        "firstName": "Fares",
        "lastName": "Ladassi",
        "bloodType": "O+",
        "ph": "ccEek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265673",
        "updatedAt": "2025-06-15T23:58:53.265675"
      },
      {
        "firstName": "Salsabil",
        "lastName": "Bousaada",
        "bloodType": "O+",
        "ph": "ccEek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265679",
        "updatedAt": "2025-06-15T23:58:53.265681"
      },
      {
        "firstName": "Lydia",
        "lastName": "Torki",
        "bloodType": "A+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": true,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265684",
        "updatedAt": "2025-06-15T23:58:53.265686"
      },
      {
        "firstName": "Oussama",
        "lastName": "Farrah",
        "bloodType": "B+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265690",
        "updatedAt": "2025-06-15T23:58:53.265692"
      },
      {
        "firstName": "Malika",
        "lastName": "Bouziane",
        "bloodType": "A+",
        "ph": "cceek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265696",
        "updatedAt": "2025-06-15T23:58:53.265697"
      },
      {
        "firstName": "Hadjer",
        "lastName": "Bouteldji",
        "bloodType": "O+",
        "ph": "ccEek-",
        "hasF": true,
        "hasC": false,
        "hasL": true,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265701",
        "updatedAt": "2025-06-15T23:58:53.265703"
      },
      {
        "firstName": "Louai",
        "lastName": "Mebrouj",
        "bloodType": "O+",
        "ph": "CcEEK-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265707",
        "updatedAt": "2025-06-15T23:58:53.265709"
      },
      {
        "firstName": "Chaima",
        "lastName": "Benchaabane",
        "bloodType": "A+",
        "ph": "cceek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265714",
        "updatedAt": "2025-06-15T23:58:53.265716"
      },
      {
        "firstName": "Wiam",
        "lastName": "Bey",
        "bloodType": "O+",
        "ph": "cceek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265720",
        "updatedAt": "2025-06-15T23:58:53.265722"
      },
      {
        "firstName": "Chaiμα",
        "lastName": "Ferdi",
        "bloodType": "A+",
        "ph": "cceek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265727",
        "updatedAt": "2025-06-15T23:58:53.265729"
      },
      {
        "firstName": "Adel",
        "lastName": "Maaemri",
        "bloodType": "O+",
        "ph": "CCeek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265732",
        "updatedAt": "2025-06-15T23:58:53.265734"
      },
      {
        "firstName": "Yaakoub",
        "lastName": "Azzizi",
        "bloodType": "A+",
        "ph": "cceek-",
        "hasF": false,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265738",
        "updatedAt": "2025-06-15T23:58:53.265740"
      },
      {
        "firstName": "Sfi",
        "lastName": "You",
        "bloodType": "B+",
        "ph": "Cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265744",
        "updatedAt": "2025-06-15T23:58:53.265745"
      },
      {
        "firstName": "A-Rahmene",
        "lastName": "Kharouzi",
        "bloodType": "O+",
        "ph": "cceek-",
        "hasF": true,
        "hasC": false,
        "hasL": false,
        "notes": null,
        "wilaya": null,
        "status": "active",
        "patientCategory": "Echanges",
        "createdAt": "2025-06-15T23:58:53.265749",
        "updatedAt": "2025-06-15T23:58:53.265752"
      }
    ]

    // Insert sample patients
    const patientsCollection = db.collection("patients")
    const patientResult = await patientsCollection.insertMany(samplePatients)
    console.log(`✅ Inserted ${patientResult.insertedCount} patients`)

    // Sample transfusions data
    const today = new Date()
    const tomorrow = new Date(today)
    tomorrow.setDate(tomorrow.getDate() + 1)

    const sampleTransfusions = [
      {
        transfusionId: "TRN001001",
        patientId: patientResult.insertedIds[0],
        scheduledDate: today,
        scheduledTime: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 9, 0, 0),
        priority: "regular",
        status: "scheduled",
        bloodUnits: 2,
        notes: "Regular scheduled transfusion for maintenance therapy",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        transfusionId: "TRN001002",
        patientId: patientResult.insertedIds[1],
        scheduledDate: today,
        scheduledTime: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 14, 30, 0),
        priority: "urgent",
        status: "scheduled",
        bloodUnits: 1,
        notes: "Urgent transfusion needed due to low hemoglobin levels",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        transfusionId: "TRN001003",
        patientId: patientResult.insertedIds[2],
        scheduledDate: tomorrow,
        scheduledTime: new Date(tomorrow.getFullYear(), tomorrow.getMonth(), tomorrow.getDate(), 10, 0, 0),
        priority: "regular",
        status: "scheduled",
        bloodUnits: 2,
        notes: "Follow-up transfusion as part of treatment plan",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        transfusionId: "TRN001004",
        patientId: patientResult.insertedIds[3],
        scheduledDate: tomorrow,
        scheduledTime: new Date(tomorrow.getFullYear(), tomorrow.getMonth(), tomorrow.getDate(), 15, 0, 0),
        priority: "urgent",
        status: "scheduled",
        bloodUnits: 3,
        notes: "Emergency transfusion for severe anemia",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        transfusionId: "TRN001005",
        patientId: patientResult.insertedIds[4],
        scheduledDate: today,
        scheduledTime: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 11, 30, 0),
        priority: "regular",
        status: "in-progress",
        bloodUnits: 1,
        notes: "Routine transfusion for chronic condition management",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]

    // Insert sample transfusions
    const transfusionsCollection = db.collection("transfusions")
    const transfusionResult = await transfusionsCollection.insertMany(sampleTransfusions)
    console.log(`✅ Inserted ${transfusionResult.insertedCount} transfusions`)

    // Create indexes for better performance
    await patientsCollection.createIndex({ patientId: 1 }, { unique: true })
    await patientsCollection.createIndex({ lastName: 1, firstName: 1 })
    await patientsCollection.createIndex({ bloodType: 1 })
    await patientsCollection.createIndex({ phone: 1 })
    await patientsCollection.createIndex({ status: 1 })
    await patientsCollection.createIndex({ patientCategory: 1 })
    await patientsCollection.createIndex({ hasF: 1 })
    await patientsCollection.createIndex({ hasC: 1 })
    await patientsCollection.createIndex({ hasL: 1 })

    await transfusionsCollection.createIndex({ transfusionId: 1 }, { unique: true })
    await transfusionsCollection.createIndex({ scheduledDate: 1 })
    await transfusionsCollection.createIndex({ patientId: 1 })
    await transfusionsCollection.createIndex({ priority: 1, status: 1 })
    await transfusionsCollection.createIndex({ status: 1 })

    console.log("✅ Created database indexes")
    console.log("🎉 Database seeded successfully!")

    // Display summary
    console.log("\n📊 Database Summary:")
    console.log(`   • Patients: ${patientResult.insertedCount}`)
    console.log(`   • Transfusions: ${transfusionResult.insertedCount}`)
    console.log(
      `   • Today's appointments: ${sampleTransfusions.filter((t) => t.scheduledDate.toDateString() === today.toDateString()).length}`,
    )
    console.log(
      `   • Tomorrow's appointments: ${sampleTransfusions.filter((t) => t.scheduledDate.toDateString() === tomorrow.toDateString()).length}`,
    )
  } catch (error) {
    console.error("❌ Error seeding database:", error)
  } finally {
    await client.close()
  }
}

seedDatabase()
